name: cbor
description: A CBOR library for Dart. An RFC7049 compliant encoding/decoding CBOR implementation.
version: 4.1.0
homepage: https://github.com/shamblett/cbor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: "^1.15.0"
  typed_data: "^1.3.0"
  convert: "^3.0.0"
  ieee754: "^1.0.3"
  meta: "^1.3.0"

dev_dependencies:
  test: "^1.16.2"
  pedantic: "^1.10.0"
  hex: ^0.2.0
