name: cbor
description: A CBOR library for Dart. An RFC7049 compliant encoding/decoding CBOR implementation.
version: 2.0.4
homepage: https://github.com/shamblett/cbor

environment:
 sdk: '>=2.0.0 <3.0.0'

dependencies:
 typed_data: '^1.1.6'

dev_dependencies:
 test: '^1.3.0'
 coverage: '^0.12.4'
 dart_dev: '^2.1.0'
 dart_style: '^1.1.3'
 build_runner: '^0.10.0'
 build_test: '^0.10.2'
 build_web_compilers: '^0.4.0'

