name: cbor
description: A CBOR library for Dart. An RFC8949 compliant encoding/decoding CBOR implementation.
version: 5.1.2
repository: https://github.com/shamblett/cbor
homepage: https://github.com/shamblett/cbor

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: "^1.15.0"
  typed_data: "^1.3.0"
  hex: '^0.2.0'
  convert: "^3.0.0"
  ieee754: "^1.0.3"
  meta: "^1.3.0"

dev_dependencies:
  test: "^1.16.2"
  lints: '^1.0.1'
