name: cbor
description: A CBOR library for Dart
version: 0.0.1
author: Steve Hamblett <steve.hamblett@linux.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
 typed_data: '>=1.1.3'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
