name: cbor
description: A CBOR library for Dart. An RFC7049 compliant encoding/decoding CBOR implementation.
version: 2.0.4
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/cbor

environment:
 sdk: '>=2.0.0 <3.0.0'

dependencies:
 typed_data: '^1.1.6'

dev_dependencies:
 test: '^1.9.4'
 build_runner: '^1.7.2'
 build_test: '^0.10.10'
 build_web_compilers: '^2.7.1'


