name: cbor
description: A CBOR library for Dart
version: 0.0.1
author: Steve Hamblett <steve.hamblett@linux.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
 typed_data:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
